// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.6.1
// - protoc             v3.21.9
// source: pmt/v1/publish.proto

package v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationPublishPub = "/api.pmt.v1.Publish/Pub"

type PublishHTTPServer interface {
	Pub(context.Context, *PubRequest) (*PubReply, error)
}

func RegisterPublishHTTPServer(s *http.Server, srv PublishHTTPServer) {
	r := s.Route("/")
	r.POST("/api/publish/v1/pub", _Publish_Pub0_HTTP_Handler(srv))
}

func _Publish_Pub0_HTTP_Handler(srv PublishHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in PubRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationPublishPub)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.Pub(ctx, req.(*PubRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*PubReply)
		return ctx.Result(200, reply)
	}
}

type PublishHTTPClient interface {
	Pub(ctx context.Context, req *PubRequest, opts ...http.CallOption) (rsp *PubReply, err error)
}

type PublishHTTPClientImpl struct {
	cc *http.Client
}

func NewPublishHTTPClient(client *http.Client) PublishHTTPClient {
	return &PublishHTTPClientImpl{client}
}

func (c *PublishHTTPClientImpl) Pub(ctx context.Context, in *PubRequest, opts ...http.CallOption) (*PubReply, error) {
	var out PubReply
	pattern := "/api/publish/v1/pub"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationPublishPub))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
